### ISSUE TITLE
【Bug】 check perfmon network data rx_bytes, rx_packets

### ISSUE THREAD

**Issue by myungkyojung** [SonicCloudOrg/sonic-ios-bridge#53] opened 2023-01-02 07:37 UTC
**在提出此issue时，我确认了以下几点（保存后请点击复选框）：**

- [x] 我已自己确认这是Sonic自身的Bug。
- [x] 我接受此issue可能被关闭，并查看开发人员的建议。

**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is.

**the values ​​of rx_bytes and rx_packets have changed!!!**

./sib -u [MYUDID] perfmon --proc-network --bundleId com.xxx.yyy
{"type":"network-connection-update","timestamp":1672644565,"rx_bytes":1879,"rx_packets":193880,"tx_bytes":167,"tx_packets":28296,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644565,"rx_bytes":1960,"rx_packets":163127,"tx_bytes":221,"tx_packets":37527,"connection_serial":33}
{"type":"network-connection-update","timestamp":1672644565,"rx_bytes":41,"rx_packets":5554,"tx_bytes":47,"tx_packets":17588,"rx_dups":53,"tx_retx":1489,"connection_serial":19}
{"type":"network-connection-update","timestamp":1672644565,"rx_bytes":18,"rx_packets":7214,"tx_bytes":15,"tx_packets":838,"tx_retx":33,"connection_serial":12}
{"type":"network-connection-update","timestamp":1672644570,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644570,"rx_bytes":1,"rx_packets":47,"tx_bytes":0,"tx_packets":0,"connection_serial":33}
{"type":"network-connection-update","timestamp":1672644577,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644577,"rx_bytes":1,"rx_packets":47,"tx_bytes":0,"tx_packets":0,"connection_serial":33}
{"type":"network-connection-update","timestamp":1672644578,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644578,"rx_bytes":1,"rx_packets":47,"tx_bytes":0,"tx_packets":0,"connection_serial":33}
{"type":"network-connection-update","timestamp":1672644581,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644581,"rx_bytes":1,"rx_packets":47,"tx_bytes":0,"tx_packets":0,"connection_serial":33}
{"type":"network-connection-update","timestamp":1672644589,"rx_bytes":1,"rx_packets":33,"tx_bytes":1,"tx_packets":33,"connection_serial":12}
{"type":"network-connection-update","timestamp":1672644590,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}
{"type":"network-connection-update","timestamp":1672644590,"rx_bytes":1,"rx_packets":47,"tx_bytes":0,"tx_packets":0,"connection_serial":33}

**版本**
Sonic的版本号 | Sonic's Version.
部署的系统(mac,windows32...) |  System
macOS bigsur 11.6.5

**Comment by ZhouYixun** [comment] 2023-01-02 07:49
What's your SIB version? v1.3.5?

**Comment by ZhouYixun** [comment] 2023-01-02 08:20
What problems have you encountered? Can you describe them in more detail?

**Comment by myungkyojung** [comment] 2023-01-02 09:01
SIB version is v1.3.6
i think the value of rx_bytes should be 75. not 1.

update","timestamp":1672644570,"rx_bytes":1,"rx_packets":75,"tx_bytes":0,"tx_packets":0,"connection_serial":34}

**Comment by ZhouYixun** [comment] 2023-01-02 09:05
Is your application always in the foreground?

**Comment by myungkyojung** [comment] 2023-01-02 09:08
yes!
first, run my app.
and execute sib command.

**Comment by ZhouYixun** [comment] 2023-01-02 09:49
> yes! first, run my app in the foreground. and execute sib command.

rx_bytes and rx_packets are not necessarily the same. It looks like few network interactions.

**Comment by ZhouYixun** [comment] 2023-01-02 09:59
> yes! first, run my app in the foreground. and execute sib command.

We continue to pay attention to this performance indicator. If it is confirmed that there is an exception, we will update the progress on this issue. Thank you for your feedback

**Comment by myungkyojung** [comment] 2023-01-03 00:55
sorry for the lack of explanation and thank for your attention.
I mean the value of rx_bytes should be the value of rx_packets and vice-versa.
compared to tidevice for the same case, the result of tidevice is rx_bytes = 75, rx_packets = 1.
but, the result of sib is rx_bytes = 1, rx_packets = 75.
thanks.

**Comment by ZhouYixun** [comment] 2023-01-03 02:46
> sorry for the lack of explanation and thank you for your attention. I mean the value of rx_bytes should be the value of rx_packets and vice-versa. compared to tidevice for the same case, the result of tidevice is rx_bytes = 75, rx_packets = 1. but, the result of sib is rx_bytes = 1, rx_packets = 75. thanks.

We will check it later, thanks.

**Comment by ZhouYixun** [comment] 2023-01-03 14:36
We fixed it in https://github.com/SonicCloudOrg/sonic-gidevice/commit/e6c7937daf6f8dbb1e502a3d897e6297d0cabc9a

You can use sib [v1.3.7](https://github.com/SonicCloudOrg/sonic-ios-bridge/releases/tag/v1.3.7) and retry it! 

We will close the issue later. If you still encounter this problem, please reopen it

**Closed by ZhouYixun** 2023-01-03 14:36 UTC
Labels: good first issue
